#129: Added Git Pre Commit Hook for ESLint and Jest

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,51 +1,57 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
-ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
 
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$')
+BIN_PATH="$(git rev-parse --show-toplevel)/node_modules/.bin"
+
+eslint() {
+  ESLINT="$BIN_PATH/eslint"
+
+  # Check for eslint
+  if [[ ! -x "$ESLINT" ]]; then
+    printf "\t\033[41mPlease install ESLint\033[0m\n"
+    exit 1
+  fi
+
+  echo "Linting modified files"
+
+  echo $STAGED_FILES | xargs $ESLINT
+
+  if [[ $? == 0 ]]; then
+    printf "\n\033[1;32mLint Passed\033[0m\n"
+  else
+    printf "\n\033[41mLint Failed:\033[0m Fix lint errors and try again!\n"
+    exit 1
+  fi
+}
+
+jest() {
+  JEST="$BIN_PATH/jest"
+
+  # Check for jest
+  if [[ ! -x "$JEST" ]]; then
+    printf "\t\033[41mPlease install Jest\033[0m\n"
+    exit 1
+  fi
+
+  echo "Testing related to modified files"
+
+  $JEST --bail --findRelatedTests $STAGED_FILES
+
+  if [[ $? == 0 ]]; then
+    printf "\n\033[1;32mTest Passed\033[0m\n"
+  else
+    printf "\n\033[41mTest Failed:\033[0m Fix test errors and try again!\n"
+    exit 1
+  fi
+}
+
+# Exit if no files modified
 if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
-PASS=true
-
-printf "\nValidating Javascript:\n"
-
-# Check for eslint
-if [[ ! -x "$ESLINT" ]]; then
-  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
-  exit 1
-fi
-
-for FILE in $STAGED_FILES
-do
-  "$ESLINT" "$FILE"
-
-  if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mESLint Passed: $FILE\033[0m"
-  else
-    printf "\t\033[41mESLint Failed: $FILE\033[0m"
-    PASS=false
-  fi
-done
-
-do
-  jest
-  if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mJest Tests: $FILE\033[0m"
-  else
-    printf "\t\033[41mJest Tests: $FILE\033[0m"
-    PASS=false
-  fi
-done
-
-printf "\nJavascript validation completed!\n"
-
-if ! $PASS; then
-  printf "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
-  exit 1
-else
-  printf "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-fi
+eslint
+jest
 
 exit $?
